os: linux

dist: xenial

language: python

python:
  - "3.5"

cache: pip

install:
  - pip install --upgrade "pip < 19.1" -r CI/requirements.txt
  - python setup.py develop

script:
  - pytest

# before_cache:
#   - remove-old-files.py -o 180 ~/.cache/pip

# deploy:
#   provider: script
#   script: echo "this is a test" && sh ./CIscripts/travisci-release

