os: linux

dist: xenial

language: python

python:
  - "3.7"

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    env: TOXENV=py37

before_install:
  - |
    echo "compiling..."
install:
  - travis_retry pip install --upgrade "pip < 19.1" setuptools tox ppu

deploy:
  provider: script
  script: CIscripts/travisci-release
