os: linux

dist: xenial

language: python

python:
  - "3.7"

cache: pip

addons:
  apt:
    packages:
      - patchelf

matrix:
  include:
  - os: osx
    language: generic
    env: TOXENV=py35
  - os: osx
    language: generic
    env: TOXENV=py36
  - os: osx
    language: generic
    env: TOXENV=py37

  fast_finish: true

before_install:
  - export OMP_NUM_THREADS=4
  # Using https://github.com/sashkab/homebrew-python for dealing with python installation
  - |
    if [ "$TRAVIS_OS_NAME" == 'osx' ]; then
      brew install llvm libomp;
      export CPP=/usr/local/opt/llvm/bin/clang;
      export PATH="/usr/local/opt/llvm/bin:$PATH";
      REQUIRED_PYTHON_VERSION=$(python -c "import os; toxenv = os.environ['TOXENV']; print('.'.join(list(toxenv[2:])))");
      brew install sashkab/python/python@$REQUIRED_PYTHON_VERSION
      /usr/local/opt/python@$REQUIRED_PYTHON_VERSION/bin/python$REQUIRED_PYTHON_VERSION -mvenv venv
      source venv/bin/activate
    fi

install:
  - pip install --upgrade "pip < 19.1" -r CI/requirements.txt
  - python setup.py develop

script:
  - pytest

deploy:
  provider: script
  script: sh CI/travis-ci-release.sh
