os: linux

dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install --upgrade "pip < 19.1" -r CI/requirements.txt
  - python setup.py develop

script:
  - pytest

deploy:
  provider: script
  script: python setup.py sdist && twine upload --repository-url $TWINE_REPOSITORY_URL --skip-existing dist/cpt-*.tar.gz -u $TWINE_USERNAME -p $TWINE_PASSWORD
